#
# Copyright (c) 2025 David Marker <dave@freedave.net>
#
# SPDX-License-Identifier: BSD-2-Clause
#

# XXX should this be /usr/local/include/netgraph ??
INCSDIR= /usr/include/netgraph
INCS=	\
	ng_pcap.h	\
	ng_ula4tag.h	\
	ng_wormhole.h

# Hacky way to get include files installed
.include <bsd.lib.mk>
