#
# Copyright (c) 2025 David Marker <dave@freedave.net>
#
# SPDX-License-Identifier: BSD-2-Clause
#

# The kernel modules go with all the others in /boot/modules
# XXX so where do man pages and inclues go? LOCABASE?
#LOCALBASE?=/usr/local
#SHAREDIR=${LOCALBASE}/share

MAN=	\
	ng_ula4tag.4 \
	ng_wormhole.4

.include <bsd.prog.mk>
