#
# Copyright (c) 2025 David Marker <dave@freedave.net>
#
# SPDX-License-Identifier: BSD-2-Clause
#

# kernel modules go with all the other (out of tree) modules in /boot/modules
LOCALBASE?=/usr/local
SHAREDIR=${LOCALBASE}/share

DIRS+=	MAN4
MAN4=	${MANDIR}4

MAN=	\
	ng_pcap.4 \
	ng_ula4tag.4 \
	ng_wormhole.4

.include <bsd.prog.mk>
